In [1]:
import numpy as np
import matplotlib as plt

In [2]:
x = np.linspace(1, 5, 5)
y = np.linspace(1, 5, 5)

In [3]:
xv, yv = np.meshgrid(x, y)
print(x, y,"\n\n")
print(xv, "\n\n", yv)

[ 1.  2.  3.  4.  5.] [ 1.  2.  3.  4.  5.] 


[[ 1.  2.  3.  4.  5.]
 [ 1.  2.  3.  4.  5.]
 [ 1.  2.  3.  4.  5.]
 [ 1.  2.  3.  4.  5.]
 [ 1.  2.  3.  4.  5.]] 

 [[ 1.  1.  1.  1.  1.]
 [ 2.  2.  2.  2.  2.]
 [ 3.  3.  3.  3.  3.]
 [ 4.  4.  4.  4.  4.]
 [ 5.  5.  5.  5.  5.]]


In [4]:
print(np.sin(xv)+np.cos(yv))

[[ 1.38177329  1.44959973  0.68142231 -0.21650019 -0.41862197]
 [ 0.42532415  0.49315059 -0.27502683 -1.17294933 -1.37507111]
 [-0.14852151 -0.08069507 -0.84887249 -1.74679499 -1.94891677]
 [ 0.18782736  0.25565381 -0.51252361 -1.41044612 -1.6125679 ]
 [ 1.12513317  1.19295961  0.42478219 -0.47314031 -0.67526209]]


In [5]:
np.sqrt(xv**2+yv**2)

array([[ 1.41421356,  2.23606798,  3.16227766,  4.12310563,  5.09901951],
       [ 2.23606798,  2.82842712,  3.60555128,  4.47213595,  5.38516481],
       [ 3.16227766,  3.60555128,  4.24264069,  5.        ,  5.83095189],
       [ 4.12310563,  4.47213595,  5.        ,  5.65685425,  6.40312424],
       [ 5.09901951,  5.38516481,  5.83095189,  6.40312424,  7.07106781]])

In [6]:
plt.contour(x, y, np.sqrt(xv**2+yv**2))

AttributeError: 'module' object has no attribute 'contour'